version: "2.0" 
services:
  csvserver:
    build: .
    container_name: con1
    ports:
      - "9393:9300"
    environment:
      - CSVSERVER_BORDER=orange
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
volumes:
   prometheus-data: 
